/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.gerador.view;

import javax.swing.JTextField;

/**
 *
 * @author lucaspdc21
 */
public class Tela_pricipal extends javax.swing.JFrame {
    

    /**
     * Creates new form Tela_pricipal
     */
    public Tela_pricipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expressao_input = new javax.swing.JTextField();
        botao_A = new javax.swing.JButton();
        botao_b = new javax.swing.JButton();
        botao_c = new javax.swing.JButton();
        botao_d = new javax.swing.JButton();
        botao_e = new javax.swing.JButton();
        botao_and = new javax.swing.JButton();
        botao_neg = new javax.swing.JButton();
        botao_or = new javax.swing.JButton();
        botao_fecha_parenteses = new javax.swing.JButton();
        botao_e1 = new javax.swing.JButton();
        botao_abre_parentese = new javax.swing.JButton();
        gerar_tabela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        aviso_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        expressao_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressao_inputActionPerformed(evt);
            }
        });

        botao_A.setText("A");
        botao_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_AActionPerformed(evt);
            }
        });

        botao_b.setText("B");
        botao_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_bActionPerformed(evt);
            }
        });

        botao_c.setText("C");
        botao_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cActionPerformed(evt);
            }
        });

        botao_d.setText("D");
        botao_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_dActionPerformed(evt);
            }
        });

        botao_e.setText("E");
        botao_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_eActionPerformed(evt);
            }
        });

        botao_and.setText("^");
        botao_and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_andActionPerformed(evt);
            }
        });

        botao_neg.setText("~");
        botao_neg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_negActionPerformed(evt);
            }
        });

        botao_or.setText("v");
        botao_or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_orActionPerformed(evt);
            }
        });

        botao_fecha_parenteses.setText(")");
        botao_fecha_parenteses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_fecha_parentesesActionPerformed(evt);
            }
        });

        botao_e1.setText("R");
        botao_e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_e1ActionPerformed(evt);
            }
        });

        botao_abre_parentese.setText("(");
        botao_abre_parentese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_abre_parenteseActionPerformed(evt);
            }
        });

        gerar_tabela.setText("Gerar tabela verdade");
        gerar_tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerar_tabelaActionPerformed(evt);
            }
        });

        aviso_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aviso_label.setText("Digite a expressão abaixo");
        aviso_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gerar_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(expressao_input)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao_A, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botao_b, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botao_c, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botao_d, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botao_e, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(botao_and, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botao_neg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao_abre_parentese, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botao_or, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(botao_e1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botao_fecha_parenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(aviso_label)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aviso_label)))
                .addGap(18, 18, 18)
                .addComponent(expressao_input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_A, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_c, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_d, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_e, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_and, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_neg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_or, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_e1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_fecha_parenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_abre_parentese, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(gerar_tabela)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cActionPerformed
        String field_String = expressao_input.getText() + "C";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_cActionPerformed

    private void botao_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_dActionPerformed
        String field_String = expressao_input.getText() + "D";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_dActionPerformed

    private void botao_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_eActionPerformed
        String field_String = expressao_input.getText() + "E";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_eActionPerformed

    private void expressao_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressao_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressao_inputActionPerformed

    private void botao_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_AActionPerformed
        String field_String = expressao_input.getText() + "A";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_AActionPerformed

    private void botao_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_bActionPerformed
        String field_String = expressao_input.getText() + "B";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_bActionPerformed

    private void botao_andActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_andActionPerformed
        String field_String = expressao_input.getText() + "^";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_andActionPerformed

    private void botao_negActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_negActionPerformed
        String field_String = expressao_input.getText() + "~";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_negActionPerformed

    private void botao_orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_orActionPerformed
        String field_String = expressao_input.getText() + "v";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_orActionPerformed

    private void botao_fecha_parentesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecha_parentesesActionPerformed
        String field_String = expressao_input.getText() + ")";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_fecha_parentesesActionPerformed

    private void botao_e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_e1ActionPerformed
        String field_String = expressao_input.getText();
        if(field_String.length() > 0){
            field_String = field_String.substring(0, field_String.length() - 1);
            expressao_input.setText(field_String);
        }
    }//GEN-LAST:event_botao_e1ActionPerformed

    private void botao_abre_parenteseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_abre_parenteseActionPerformed
        String field_String = expressao_input.getText() + "(";
        expressao_input.setText(field_String);
    }//GEN-LAST:event_botao_abre_parenteseActionPerformed

    private void gerar_tabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerar_tabelaActionPerformed
        if(verificarValidacao(expressao_input) == true){
            abrirJanelaTV();        
        }else{
            aviso_label.setText("Expressao invalida");
        }  
        
    }//GEN-LAST:event_gerar_tabelaActionPerformed

    private void abrirJanelaTV(){
        Tela_tabela tela = new Tela_tabela();
        tela.setVisible(true);
    }
    
    private boolean verificarValidacao(JTextField exp){
        // chama validacao
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_pricipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso_label;
    private javax.swing.JButton botao_A;
    private javax.swing.JButton botao_abre_parentese;
    private javax.swing.JButton botao_and;
    private javax.swing.JButton botao_b;
    private javax.swing.JButton botao_c;
    private javax.swing.JButton botao_d;
    private javax.swing.JButton botao_e;
    private javax.swing.JButton botao_e1;
    private javax.swing.JButton botao_fecha_parenteses;
    private javax.swing.JButton botao_neg;
    private javax.swing.JButton botao_or;
    private javax.swing.JTextField expressao_input;
    private javax.swing.JButton gerar_tabela;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
