/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tabelaverdade.View;

import com.mycompany.tabelaverdade.Controller.CalculadoraController;
import com.mycompany.tabelaverdade.utils.Util;
import com.mycompany.tabelaverdade.Model.Formula;
import com.mycompany.tabelaverdade.Controller.FormulaValidator;
import com.mycompany.tabelaverdade.Model.LogicValue;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author luizc
 */
public class ResultadoExpressao extends javax.swing.JFrame {

    public static final HashSet<String> openedFormulas = new HashSet<String>();


    private CalculadoraController controller = new CalculadoraController();
    private Formula formula;
    private String[] variables;
    private String[][] variablesTruthValues;
    private String expression;

    public ResultadoExpressao(String formulaExpression) {
        try {
            this.formula = new Formula(formulaExpression);
        } catch (Exception e) {
            Util.ERROR("Fórmula inválida!");
            return;
        }

        if (controller.isFormulaAlreadyOpen(openedFormulas, formulaExpression)) {
            Util.ERROR("Já existe uma tabela verdade para esta fórmula aberta!");
            return;
        }

        this.expression = formulaExpression;
        try {
            this.variables = controller.extractVariables(formula);
        } catch (Exception e) {
            Util.ERROR(e.getMessage());
            return;
        }

        initComponents();
        super.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.TabelaVerdade.getTableHeader().setReorderingAllowed(false);
        super.setVisible(true);

        setTruthTable();
        setCellsColor();

        openedFormulas.add(expression);
    }

    private void setTruthTable() {
        variablesTruthValues = controller.populateVariablesTruthValues(variables);

        String[] labels = new String[variables.length + 1];
        labels[variables.length] = expression;

        for (int i = 0; i < variables.length; i++) {
            labels[i] = variables[i];
        }

        DefaultTableModel tableModel = new DefaultTableModel(variablesTruthValues, labels) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        this.TabelaVerdade.setModel(tableModel);

        controller.evaluateFormula(formula, variables, variablesTruthValues, tableModel);
    }

    private void setCellsColor() {
        if (variablesTruthValues == null) {
            return;
        }

        TableCellRenderer coloredCells = new CustomRendererForTruthTable();
        this.TabelaVerdade.setDefaultRenderer(Object.class, coloredCells);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaVerdade = new javax.swing.JTable();
        SaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela Verdade");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TabelaVerdade.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TabelaVerdade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelaVerdade);

        SaveButton.setBackground(new java.awt.Color(102, 204, 0));
        SaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Salvar");
        SaveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SaveButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveButton)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseReleased
        CalculadoraController controller = new CalculadoraController();
        controller.saveFormula(this.expression);
    }//GEN-LAST:event_SaveButtonMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ResultadoExpressao.openedFormulas.remove(this.expression);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JTable TabelaVerdade;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
